uuid = "0cfda548-32e7-4e8b-936e-99ee36e5dad1"
name = "SolitonBEC"
authors = ["lorenzifrancesco <francesco.lorenzi.2@studenti.unipd.it>"]
version = "0.1.0"

[deps]


[compat]


[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "SparseArrays", "Random", "Test"]
